<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SnoopInSpace.Domain\SnoopInSpace.Domain.csproj" />
    <ProjectReference Include="..\SnoopInSpace.Ports\SnoopInSpace.Ports.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
