<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SnoopInSpace.Adapters.InMemory\SnoopInSpace.Adapters.InMemory.csproj" />
    <ProjectReference Include="..\SnoopInSpace.Application\SnoopInSpace.Application.csproj" />
    <ProjectReference Include="..\SnoopInSpace.Ports\SnoopInSpace.Ports.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
